# Etapa de build
FROM node:24-alpine3.21 AS builder
WORKDIR /app

# Argumentos de build para configuración
ARG VITE_API_URL=http://localhost:3010/api/1.0
ARG VITE_NODE_ENV=development
ARG VITE_ENABLE_HTTPS=false
ARG VITE_APP_TITLE="DEV - Gestión de Inventarios"

# Variables de entorno para el build
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_NODE_ENV=$VITE_NODE_ENV
ENV VITE_ENABLE_HTTPS=$VITE_ENABLE_HTTPS
ENV VITE_APP_TITLE=$VITE_APP_TITLE

COPY package*.json ./
RUN npm install
RUN npm install -g vite
COPY . .


EXPOSE 3000
CMD ["npm", "run", "dev"]
